# https://hub.docker.com/_/mysql
version: "3.1"

volumes:
    my-db:

services:
    db:
        image: mysql:5.7
        # lower_case_table_names -> case insensitive
        # command: --default-authentication-plugin=mysql_native_password
        command: --lower_case_table_names=1
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: admin123
        volumes:
            - my-db:/var/lib/mysql
    # adminer:
    #     image: adminer
    #     # restart: always
    #     ports:
    #         - 8080:8080