# login with shell script: psql -h localhost -p 5432 -U zquangu112z -W

version: '3.1'
volumes:
  db-data:
services:
  postgres12_pentaho:
    image: postgres:12
    environment:
      POSTGRES_USER: 'hibuser'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
    - db-data:/var/lib/postgresql/data