# login with shell script: psql -h localhost -p 5432 -U zquangu112z -W

version: '3.1'
volumes:
  db-data:
services:
  postgres12:
    image: postgres:12
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5433:5432
    volumes:
    - db-data:/var/lib/postgresql/data